#!/usr/bin/env php
<?php

require 'vendor/autoload.php';
require 'bootstrap/env.php';

use Symfony\Component\Console\Application;

$application = new Application();

// ... register commands

$application->run();