#!/usr/bin/env php
<?php

require 'vendor/autoload.php';
require 'bootstrap/env.php';

use Symfony\Component\Console\Application;

use KickAss\Commerce\Product\Command\CacheCommand as ProductCacheCommand;
use KickAss\Toolbox\Command\ProvisionEnvironmentCommand as EnvironmentCommand;


$application = new Application("
     OCTOCLI

     -------
     | @ @ |
     -------
      ).-.(
     '/|||\\`
       '|`    

A tool with it's tentacles 
  in everything KickAss");

$application->add(new ProductCacheCommand());
$application->add(new EnvironmentCommand());

$application->run();