#!/usr/bin/env php
<?php

require 'vendor/autoload.php';
require 'bootstrap/env.php';

use Symfony\Component\Console\Application;

use KickAss\Commerce\Product\Command\CacheCommand as ProductCacheCommand;

$application = new Application("
     OCTOCLI

     -------
     | @ @ |
     -------
      ).-.(
     '/|||\\`
       '|`    

A tool with it's tenticles 
  in everything KickAss");

$application->add(new ProductCacheCommand());

$application->run();